name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # har kuni avtomatik
  workflow_dispatch:      # qo'lda ham ishlatish mumkin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: codemsodiq
          outputs: dist/snake.svg

      - name: Push Snake Animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
